stas/jsonapi.rb

README.md, lib/jsonapi/rails.rb
Hi! I recently found this repo (via [jsonapi.org](https://jsonapi.org/implementations/#server-libraries-ruby)) while evaluating JSON:API options for a new Rails 6 app and since I was already in the source I thought I'd take care of the doc error in the `jsonapi_deserialize` example noted by @dgavey in issue #3. 
Thanks for the bundle, I'm finding it a very useful way to conveniently tie together a few gems I was already considering using. 
Resolves https://github.com/stas/jsonapi.rb/issues/3
=> Fix jsonapi_deserialize example in README

Gemfile, lib/jsonapi/pagination.rb, spec/pagination_spec.rb
#4 describes two issues:
* The array pagination meta is rendering the wrong cur/prev/next pages due to the original resources being already paginated
* The paginated array is off by one due to wrong math
We are caching the original array size and using that to calculate the meta. The math is also fixed now.
@jf @petronius I will appreciate any feedback. I'll try to release the fix asap.
features)
=> Array pagination

lib/jsonapi/pagination.rb, spec/pagination_spec.rb
Continuing the discussion from #4, it looks like we still need one more fix/test for arrays. #15 was good but we need something to handle the case for when we attempt to page beyond what an array can give us. Does this make sense?
So as an example:
```
resources = [1,2,3,4,5]
offset = 20
limit = 10
resources[(offset)..(offset + limit - 1)]
=> nil
```
When we page beyond the end of the array, the next line, https://github.com/stas/jsonapi.rb/blob/fa5a0bc4b7bbfd4c2c6c6f2133ee342179a8f9de/lib/jsonapi/pagination.rb#L22 fails.
Paging beyond the end of an array does not fail.
Comments and feedback welcome. Apologies for not following the format with the checklist; I have tests, but I'm not entirely sure about ticking the CI/CD box.
=> Fix paging beyond end of array, when `resources[(offset)..(offset + limit - 1)]` may be nil

lib/jsonapi/pagination.rb
Sorry, but I just realized that there was a much more expressive and clearer way to communicate the fix than what I coded earlier. Apologies for the noise, but thought this was worth rewriting.
=> More elegant and expressive fix for #16

lib/jsonapi/pagination.rb
The idea is to use as much as possible Rack's API instead of Rails. 
@banduk would you be kind to give this branch a try please. If you find anything else, I'll be happy to take care of it. Thanks again!
Pagination module fails on non-Rails (Grape/Rack) implementations.
Pagination will fallback to Rack's API where Rails is not available.
features)
=> Remove some Rails-ism from pagination module.

lib/jsonapi/pagination.rb, spec/pagination_spec.rb
Currently, the pagination doesn't return the total number of records, which can be required on the client-side to generate pagination metadata, e.g. `1-10 of 29 widgets`.
This is referenced in #21 and #23 already, and while I agree that the `total` name proposed in #21 is confusing (could be total of pages?), the proposed solution there effectively replicates the existing functionality in `/lib/jsonapi/pagination.rb`.
Added a `records` key to the pagination, that is the total number of records being paginated.
Hopefully, this name is less confusing, and succinctly describes itself.
features)
=> Add Count of Records to Pagination

lib/jsonapi/pagination.rb
The `Pagination` module uses `#count` to calculate the total number of resources. AR's `#count` always executes an SQL `COUNT`.
Use AR's `#size` instead, which checks if the records of the AR relation have already been loaded and only executes a `COUNT` if truly necessary.
See https://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-size
features)
=> Use `#size` instead of `#count` for pagination

README.md, lib/jsonapi/pagination.rb
Default per-page is 30 and set using a constant. Pagination meta does not include total number of records.
Implementers may now configure the default per-page by defining a method. Total number of records is included in the pagination meta.
features)
=> Total count and configurable default per_page

.github/workflows/ci.yml, lib/jsonapi/rails.rb, spec/errors_spec.rb
Starting with Rails 6.1 `ActiveModel::Error` is an actual class:
> Active Model's errors are now objects with an interface that allows
> your application to more easily handle and interact with errors thrown
> by models. The feature[1] includes a query interface, enables more
> precise testing, and access to error details.
>
> [1] rails/rails#32313
As a result of this `resource.details` looks slightly different than in
previous versions and [notably doesn't contain `:message`](https://github.com/rails/rails/blob/2a7ff0a5f54979b14b19f827c99295297dda411d/activemodel/lib/active_model/error.rb#L149) anymore, if
`object.errors.add(:something, message: 'some error')` was used to specify a validation error.
[This causes the json payload for validation errors not to contain the specified message …
=> Handle Rails 6.1 ActiveModel::Error#detail

README.md, lib/jsonapi/pagination.rb
related to issue https://github.com/stas/jsonapi.rb/issues/37
if you set the params `page[size]` in the query, `jsonapi_page_size` is not called and `page[size]` is used to determine  the page size of the paginated response.
always call the module method `jsonapi_page_size` and pass the value of the query param `page[size]` to the method to define the page size of the paginated response. Fallback to `JSONAPI_PAGE_SIZE` if `page[size]` is lower than 1 or not present in the query string at all.
features)
=> always call jsonapi_page_size method on pagination enabled requests

.github/workflows/ci.yml, README.md, Rakefile, jsonapi.rb.gemspec, lib/jsonapi/filtering.rb, lib/jsonapi/rails.rb, spec/dummy.rb, spec/errors_spec.rb
Non-collection objects with `size` attribute are mistakenly treated as collections, causing serialization to fail (see #75).
Only `Enumerables` are treated as collections, cf. [the corresponding method in jsonapi-serializer](https://github.com/jsonapi-serializer/jsonapi-serializer/blob/v2.2.0/lib/fast_jsonapi/object_serializer.rb#L115).
Fixes #75.
features)
It looks like the build may be currently failing for other reasons?
=> Use is_a?(Enumerable) instead of respond_to?(:size) to detect collections

lib/jsonapi/rails.rb
> DEPRECATION WARNING: Rails 6.1 will return Content-Type header without modification. If you want just the MIME type, please use `#media_type` instead. (called from block (2 levels) in index at /app/app/controllers/api/v1/users_controller.rb:33)
Rails version: 6.0.4
Ruby version: 2.7.3
=> Fix deprecation warning with Content-Type header without modification

lib/jsonapi/rails.rb
Currently in the rendered, if it's a collection but there aren't any resources, the `meta` and `links` fields are returned in the json, even if they are nil. However, if there are more than one resource, the `links` and `meta` data fields will be remove if they are nil. 
Now we'll be removing any `links` or `meta` fields from the json if they are nil, if there aren't any resources. This matches how the serializer in jsonapi-serializer work so it's keeping behaviour consistent.
features)
=> fix: removing empty meta and link fields if data is empty to match jsonapi-serializer behaviour

.github/workflows/ci.yml, Rakefile, spec/pagination_spec.rb
Ruby 3.2 is not in the CI matrix.
CI builds fail because of Rubocop lints
Ruby 3.2 is in the CI matrix.
Rubocop passes on CI builds
features)
=> Add Ruby 3.2 to the CI matrix

spec/dummy.rb
Ransack 4 requires explicitly allowlisting ransackable attributes and associations for each model. This causes the specs to fail with the most recent Ransack version. This fixes those spec failures.
Specs will pass. 
Checklist doesn't apply as this is purely a fix for the test suite.
=> Fix specs with Ransack 4.0

.github/workflows/ci.yml, lib/jsonapi/deserialization.rb, lib/jsonapi/fetching.rb
Currently, builds are failing because of Rubocop complaining about three lines.
The build still fails because of Ransack 4 being incompatible with the library, but that's for a different PR.
features)~
=> Fix Rubocop offenses

.github/workflows/ci.yml
The CI runs fail because Ransack 4.1, which we need for Rails 7 support, is not available for Ruby < 3.0
The CI runs do not fail, and we test newer Rubies.
features)
=> CI Matrix: Drop Rails 6, Ruby 2.7

lib/jsonapi/filtering.rb
https://github.com/stas/jsonapi.rb/issues/101
Skipped requiring active record since it's a soft dependency not used directly.
features)
=> JSONAPI::Filtering: remove activerecord dependency

.github/workflows/ci.yml, lib/jsonapi/active_model_error_serializer.rb, lib/jsonapi/rails.rb, spec/dummy.rb, spec/errors_spec.rb
No behavior change, but the ActiveModel::ErrorSerializer reads much nicer.
features)
=> Refactor ActiveModel::ErrorSerializer

Rakefile, lib/jsonapi/pagination.rb, spec/dummy.rb, spec/pagination_spec.rb
This simplification allows decorating objects after they are paginated, without losing the correct total object count.
I'm using an instance variable on the including controller here, because the decorating the paginated collection will have us lose the instance variable we set on it.
Here's the case where this happens: We have a complex ActiveRecord collection that we run through Ransack and Kaminari, but before rendering we want to convert each object in it using a `SimpleDelegator`.
Here's a simplified version of the controller action we're looking at:
```
class UserDecorator < SimpleDelegator
def fantastic_for_rendering
"Whoah"
end
end
def index
allowed_fields = [
:first_name, :last_name, :created_at,
:notes_created_at, :notes_quantity
]
options = { sort_with_expressions: true } …
```
=> Allow decorating objects after pagination

.github/workflows/ci.yml, jsonapi.rb.gemspec
CI is running with EOL/old dependencies.
Removed Rails v6 and v5 old deps.
features)
=> Cleanup CI config.
